-------------------------------------------------------------------------------
Test set: models.AnimalTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 1.941 sec <<< FAILURE! - in models.AnimalTest
save_assignsIdToObjectAndSavesObjectToDatabase(models.AnimalTest)  Time elapsed: 0.475 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.save_assignsIdToObjectAndSavesObjectToDatabase(AnimalTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.save_assignsIdToObjectAndSavesObjectToDatabase(AnimalTest.java:31)

delete_deletesAnimalFromDatabase_0(models.AnimalTest)  Time elapsed: 0.473 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.delete_deletesAnimalFromDatabase_0(AnimalTest.java:58)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.delete_deletesAnimalFromDatabase_0(AnimalTest.java:58)

all_returnsAllInstancesOfAnimal_false(models.AnimalTest)  Time elapsed: 0.482 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.all_returnsAllInstancesOfAnimal_false(AnimalTest.java:39)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.all_returnsAllInstancesOfAnimal_false(AnimalTest.java:39)

find_returnsAnimalWithSameId_secondAnimal(models.AnimalTest)  Time elapsed: 0.509 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.find_returnsAnimalWithSameId_secondAnimal(AnimalTest.java:49)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.AnimalTest.find_returnsAnimalWithSameId_secondAnimal(AnimalTest.java:49)

